name: Scraper AFNIC

on:
  schedule:
    - cron: "0 4 * * *"  # Exécution tous les jours à 4h UTC
  workflow_dispatch:  # Permet d'exécuter manuellement si besoin

permissions:
  contents: write  # 🔥 Ajouté ici pour permettre le commit automatique

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token GitHub

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install python-whois pandas requests schedule

      - name: Exécuter le scraper
        run: python whois_scraper.py

      - name: Commit & Push des résultats
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.csv  # ✅ Ajoute seulement les fichiers CSV dans le dossier principal
          git commit -m "Mise à jour des leads AFNIC - $(date '+%Y-%m-%d')" || echo "Rien à committer"
          git push

